package com.mealnotificator.model;
// Generated Dec 13, 2017 5:09:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="address"
    ,catalog="MealManager"
)
public class Address  implements java.io.Serializable {


     private Integer idAddress;
     private Street street;
     private Integer number;
     private Set<User> users = new HashSet<User>(0);

    public Address() {
    }

    public Address(Street street, Integer number, Set<User> users) {
       this.street = street;
       this.number = number;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idAddress", unique=true, nullable=false)
    public Integer getIdAddress() {
        return this.idAddress;
    }
    
    public void setIdAddress(Integer idAddress) {
        this.idAddress = idAddress;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idStreet")
    public Street getStreet() {
        return this.street;
    }
    
    public void setStreet(Street street) {
        this.street = street;
    }

    
    @Column(name="number")
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


