package com.mealnotificator.model;
// Generated Dec 21, 2017 4:42:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="MealManager"
)
public class City  implements java.io.Serializable {


     private Integer idCity;
     private State state;
     private String name;
     private Set<Address> addresses = new HashSet<Address>(0);

    public City() {
    }

    public City(State state, String name, Set<Address> addresses) {
       this.state = state;
       this.name = name;
       this.addresses = addresses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCity", unique=true, nullable=false)
    public Integer getIdCity() {
        return this.idCity;
    }
    
    public void setIdCity(Integer idCity) {
        this.idCity = idCity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idState")
    public State getState() {
        return this.state;
    }
    
    public void setState(State state) {
        this.state = state;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="city")
    public Set<Address> getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }




}


