package com.mealnotificator.model;
// Generated Dec 13, 2017 5:09:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Ingredient generated by hbm2java
 */
@Entity
@Table(name="ingredient"
    ,catalog="MealManager"
)
public class Ingredient  implements java.io.Serializable {


     private Integer idIngredient;
     private String name;
     private Set<Meal> meals = new HashSet<Meal>(0);

    public Ingredient() {
    }

    public Ingredient(String name, Set<Meal> meals) {
       this.name = name;
       this.meals = meals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idIngredient", unique=true, nullable=false)
    public Integer getIdIngredient() {
        return this.idIngredient;
    }
    
    public void setIdIngredient(Integer idIngredient) {
        this.idIngredient = idIngredient;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="ingredients")
    public Set<Meal> getMeals() {
        return this.meals;
    }
    
    public void setMeals(Set<Meal> meals) {
        this.meals = meals;
    }




}


