package com.mealnotificator.model;
// Generated Dec 13, 2017 5:09:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Meal generated by hbm2java
 */
@Entity
@Table(name="meal"
    ,catalog="MealManager"
)
public class Meal  implements java.io.Serializable {


     private Integer idMeal;
     private Instituition instituition;
     private String name;
     private Date mealDate;
     private String description;
     private String recipe;
     private Set<Ingredient> ingredients = new HashSet<Ingredient>(0);

    public Meal() {
    }

    public Meal(Instituition instituition, String name, Date mealDate, String description, String recipe, Set<Ingredient> ingredients) {
       this.instituition = instituition;
       this.name = name;
       this.mealDate = mealDate;
       this.description = description;
       this.recipe = recipe;
       this.ingredients = ingredients;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idMeal", unique=true, nullable=false)
    public Integer getIdMeal() {
        return this.idMeal;
    }
    
    public void setIdMeal(Integer idMeal) {
        this.idMeal = idMeal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idInstituition")
    public Instituition getInstituition() {
        return this.instituition;
    }
    
    public void setInstituition(Instituition instituition) {
        this.instituition = instituition;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mealDate", length=10)
    public Date getMealDate() {
        return this.mealDate;
    }
    
    public void setMealDate(Date mealDate) {
        this.mealDate = mealDate;
    }

    
    @Column(name="description", length=150)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="recipe", length=500)
    public String getRecipe() {
        return this.recipe;
    }
    
    public void setRecipe(String recipe) {
        this.recipe = recipe;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="mealIngredients", catalog="MealManager", joinColumns = { 
        @JoinColumn(name="idMeal", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idIngredient", nullable=false, updatable=false) })
    public Set<Ingredient> getIngredients() {
        return this.ingredients;
    }
    
    public void setIngredients(Set<Ingredient> ingredients) {
        this.ingredients = ingredients;
    }




}


