package com.mealnotificator.model;
// Generated Dec 13, 2017 5:09:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person"
    ,catalog="MealManager"
)
public class Person  implements java.io.Serializable {


     private int idUser;
     private Instituition instituition;
     private User user;
     private Date birthDay;

    public Person() {
    }

	
    public Person(Instituition instituition, User user) {
        this.instituition = instituition;
        this.user = user;
    }
    public Person(Instituition instituition, User user, Date birthDay) {
       this.instituition = instituition;
       this.user = user;
       this.birthDay = birthDay;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="user"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idUser", unique=true, nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idInstituition", nullable=false)
    public Instituition getInstituition() {
        return this.instituition;
    }
    
    public void setInstituition(Instituition instituition) {
        this.instituition = instituition;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthDay", length=10)
    public Date getBirthDay() {
        return this.birthDay;
    }
    
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }




}


