package com.mealnotificator.model;
// Generated Dec 21, 2017 4:42:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name="state"
    ,catalog="MealManager"
)
public class State  implements java.io.Serializable {


     private Integer idState;
     private String name;
     private String initials;
     private Set<City> cities = new HashSet<City>(0);

    public State() {
    }

    public State(String name, String initials, Set<City> cities) {
       this.name = name;
       this.initials = initials;
       this.cities = cities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idState", unique=true, nullable=false)
    public Integer getIdState() {
        return this.idState;
    }
    
    public void setIdState(Integer idState) {
        this.idState = idState;
    }

    
    @Column(name="name", length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="initials", length=2)
    public String getInitials() {
        return this.initials;
    }
    
    public void setInitials(String initials) {
        this.initials = initials;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="state")
    public Set<City> getCities() {
        return this.cities;
    }
    
    public void setCities(Set<City> cities) {
        this.cities = cities;
    }




}


