package com.mealnotificator.model;
// Generated Dec 13, 2017 5:09:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Street generated by hbm2java
 */
@Entity
@Table(name="street"
    ,catalog="MealManager"
)
public class Street  implements java.io.Serializable {


     private Integer idStreet;
     private City city;
     private String name;
     private String zipCode;
     private String district;
     private Set<Address> addresses = new HashSet<Address>(0);

    public Street() {
    }

    public Street(City city, String name, String zipCode, String district, Set<Address> addresses) {
       this.city = city;
       this.name = name;
       this.zipCode = zipCode;
       this.district = district;
       this.addresses = addresses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idStreet", unique=true, nullable=false)
    public Integer getIdStreet() {
        return this.idStreet;
    }
    
    public void setIdStreet(Integer idStreet) {
        this.idStreet = idStreet;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCity")
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="zipCode", length=9)
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    
    @Column(name="district", length=50)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="street")
    public Set<Address> getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }




}


