package com.mealnotificator.model;
// Generated Dec 13, 2017 5:09:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="MealManager"
)
public class User  implements java.io.Serializable {


     private Integer idUser;
     private Address address;
     private String name;
     private String email;
     private String userType;
     private Person person;
     private Instituition instituition;

    public User() {
    }

	
    public User(String userType) {
        this.userType = userType;
    }
    public User(Address address, String name, String email, String userType, Person person, Instituition instituition) {
       this.address = address;
       this.name = name;
       this.email = email;
       this.userType = userType;
       this.person = person;
       this.instituition = instituition;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idUser", unique=true, nullable=false)
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idAddress")
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", length=75)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="userType", nullable=false, length=2)
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="user")
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="user")
    public Instituition getInstituition() {
        return this.instituition;
    }
    
    public void setInstituition(Instituition instituition) {
        this.instituition = instituition;
    }




}


